-- ITQANAK foundation schema. Migrations are forward-only and executed by the
-- application runner under an advisory lock; do not edit this file once applied.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE platform_metadata (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO platform_metadata (key, value)
VALUES ('platform_foundation', jsonb_build_object('schema_version', 1))
ON CONFLICT (key) DO NOTHING;

-- Durable, idempotent event staging for the future notification pipeline.
CREATE TABLE outbox_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type TEXT NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id UUID,
  idempotency_key TEXT NOT NULL UNIQUE,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY', 'DELIVERED', 'DEAD_LETTER')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ
);

CREATE INDEX outbox_events_delivery_idx
  ON outbox_events (status, available_at, created_at);

-- A lightweight operational signal; no student data belongs in this table.
CREATE TABLE worker_heartbeats (
  worker_name TEXT PRIMARY KEY,
  last_seen_at TIMESTAMPTZ NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
