FROM postgres:17.4-alpine

RUN addgroup -S -g 10001 itqanak && adduser -S -G itqanak -u 10001 itqanak

COPY scripts/backup-postgres.sh /usr/local/bin/backup-postgres.sh
COPY scripts/restore-postgres.sh /usr/local/bin/restore-postgres.sh
COPY scripts/verify-backup.sh /usr/local/bin/verify-backup.sh

RUN chmod 0555 /usr/local/bin/backup-postgres.sh \
    /usr/local/bin/restore-postgres.sh \
    /usr/local/bin/verify-backup.sh

USER itqanak
ENTRYPOINT ["/usr/local/bin/backup-postgres.sh"]
