/** JSON-compatible payload accepted by the transactional outbox. */
export type JsonPrimitive = boolean | number | string | null;
export type JsonValue =
  | JsonPrimitive
  | readonly JsonValue[]
  | { readonly [key: string]: JsonValue };
export type JsonObject = { readonly [key: string]: JsonValue };

export const outboxStatuses = [
  "PENDING",
  "PROCESSING",
  "RETRY",
  "DELIVERED",
  "DEAD_LETTER",
] as const;
export type OutboxStatus = (typeof outboxStatuses)[number];

export interface OutboxEvent<TPayload extends JsonObject = JsonObject> {
  /** UUID generated by the producer or database. */
  readonly id: string;
  readonly aggregateType: string;
  readonly aggregateId: string;
  readonly eventType: string;
  readonly payload: TPayload;
  /** Stable producer-side key; retries must reuse it. */
  readonly idempotencyKey: string;
  readonly occurredAt: Date;
  readonly correlationId?: string;
}

export interface PendingOutboxEvent<TPayload extends JsonObject = JsonObject>
  extends Omit<OutboxEvent<TPayload>, "id" | "occurredAt"> {
  readonly id?: string;
  readonly occurredAt?: Date;
}

/**
 * Implement this on the same transaction object that writes the aggregate.
 * That is the contract which prevents an accepted request from losing its
 * notification after a process crash.
 */
export interface TransactionalOutbox<TTransaction = unknown> {
  enqueue<TPayload extends JsonObject>(
    transaction: TTransaction,
    event: PendingOutboxEvent<TPayload>,
  ): Promise<OutboxEvent<TPayload>>;
}

export interface ClaimedOutboxEvent<TPayload extends JsonObject = JsonObject>
  extends OutboxEvent<TPayload> {
  readonly status: "PROCESSING";
  readonly attempts: number;
  readonly maxAttempts: number;
  readonly availableAt: Date;
}

export interface OutboxProcessor<TTransaction = unknown> {
  claim(limit: number, workerId: string): Promise<readonly ClaimedOutboxEvent[]>;
  markDelivered(transaction: TTransaction, eventId: string): Promise<void>;
  scheduleRetry(
    transaction: TTransaction,
    eventId: string,
    availableAt: Date,
    errorCode: string,
  ): Promise<void>;
  moveToDeadLetter(transaction: TTransaction, eventId: string, errorCode: string): Promise<void>;
}
